import paths from './mapperPaths.json';

module.exports = {
  testTimeout: 10000,
  verbose: false,
  maxWorkers: '50%',
  moduleFileExtensions: ['js', 'json', 'ts'],
  testRegex: '.*\\unit.test\\.ts$',
  rootDir: 'src',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  moduleNameMapper: paths,
  collectCoverageFrom: [
    '**/*.{js,ts}',
    '**/*.(t|j)s',
    '!**/database/**',
    '!**/config/**',
    '!**/interceptors/**',
    '!**/typeorm/**',
    '!**/health/**',
    '!**/test-helpers/**',
    '!**/*.entity.{js,ts}',
    '!**/*.module.{js,ts}',
    '!**/index.{js,ts}',
    '!**/main.ts',
    '!**/modules.ts',
    '!**/app.module.ts',
    '!**/*.fixture.{js,ts}',
    '!**/fixtures.{js,ts}',
    '!**/*.dto.{js,ts}',
    '!**/*.builder.{js,ts}',
    '!**/*.test.{js,ts}',
    '!**/*.decorator.{js,ts}',
    '!**/*.aggregate.{js,ts}',
    '!**/*.controller.{js,ts}',
    '!**/*.interceptor.{js,ts}',
    '!**/shared/base/**',
    '!**/*.entities.{js,ts}',
    '!**/*.input.{js,ts}',
    '!**/*.output.{js,ts}',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
};
